#	  _____       _ _ _                 _     
#	 / ____|     (_) | |               | |  _ 
#	| (___   __ _ _| | |__   ___   __ _| |_(_)
#	 \___ \ / _` | | | '_ \ / _ \ / _` | __|  
#	 ____) | (_| | | | |_) | (_) | (_| | |_ _ 
#	|_____/ \__,_|_|_|_.__/ \___/ \__,_|\__(_)
                                          
# Basic Setup:
name = "Hello_World"
short_name = "helloworld_colewilson4"
email = "cole@colewilson.xyz"
author = "Cole Wilson"
short_description = ""
description = ""
url = "https://google.com"
keywords = ""
license = "none"
latest_build = "0.0.1+build.2"


# Resource Setup:
[resources]
icon = ""
data_files = []
modules = []
file = "main.py"
no_import = []


# Plugin Commands:


# Build Routines:
[build.homebrew]

[build.test]

[build.pyinstaller]
_run = false
type = 1
mac = true
windows = true
unix = true
bundle_id = "com.colewilson.helloworld_colewilson4"

[build.pypi.commands]
hello = ""

[build.pypi.entry_points]


# Release Routines:
[release.github]

[release.echo]
int = 1


# Other:
[git]


# Thank you for using Sailboat!